name: VMtropy build checks
on: push
jobs:
  integration-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            profile: minimal
      - uses: Swatinem/rust-cache@v2
        with:
          key:  "vmtropy"
      - run: cargo test
  clippy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          key:  "vmtropy"
      - run: cargo clippy --all-targets --all-features -- -D warnings
  format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt
      - run: cargo fmt -- --check
  # coverage:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - uses: actions/checkout@v3
  #     - run: ls
  #     - run: docker run --security-opt seccomp=unconfined -v "${PWD}:/volume" xd009642/tarpaulin
  #     - name: Upload coverage to codecov.io
  #       uses: codecov/codecov-action@v3
  #       with:
  #         fail_ci_if_error: true
